name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: prepare_docker
      run:  curl https://raw.githubusercontent.com/Heliferepo/epidump_manager/master/install_criterion.sh | sh
    - name: make_repository
      run: git clone https://github.com/EpitechIT2020/B-CPE-101-RUN-1-1-bistromatic-mattis.dalleau bistro && make tests_run -C bistro
