name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: prepare_docker
      run:  sh -c $(curl https://raw.githubusercontent.com/Heliferepo/epidump_manager/master/install_criterion.sh)
    - name: make
      run: make tests_run
